apiVersion: v1
kind: Pod
metadata:
  labels:
    servicebroker_etcd_node: instanceid-etcd0
    servicebroker: instanceid-etcd
  name: sb-instanceid-etcd0
spec:
  containers:
  - command:
    - bash 
    - /usr/bin/init-root-password.sh
    - 1234
    image: 172.30.188.59:5000/etcd-test/etcd-product
    imagePullPolicy: IfNotPresent
    name: etcd0
    ports:
    - containerPort: 2379
      name: client
      protocol: TCP
    - containerPort: 2380
      name: server
      protocol: TCP
  restartPolicy: Never
